// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearConnectionLogs() {
  return window['go']['main']['App']['ClearConnectionLogs']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DisableRule(arg1) {
  return window['go']['main']['App']['DisableRule'](arg1);
}

export function EditRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EditRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EnableRule(arg1) {
  return window['go']['main']['App']['EnableRule'](arg1);
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function SetDnsViaProxy(arg1) {
  return window['go']['main']['App']['SetDnsViaProxy'](arg1);
}

export function SetLocalhostViaProxy(arg1) {
  return window['go']['main']['App']['SetLocalhostViaProxy'](arg1);
}

export function SetProxyConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetProxyConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTrafficLogging(arg1) {
  return window['go']['main']['App']['SetTrafficLogging'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
