// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function ClearConnectionLogs():Promise<void>;

export function DeleteRule(arg1:number):Promise<boolean>;

export function DisableRule(arg1:number):Promise<boolean>;

export function EnableRule(arg1:number):Promise<boolean>;

export function GetProxyConfig():Promise<Record<string, any>>;

export function GetRules():Promise<Array<Record<string, any>>>;

export function GetStats():Promise<Record<string, any>>;

export function IsRunning():Promise<boolean>;

export function SetDnsViaProxy(arg1:boolean):Promise<void>;

export function SetLocalhostViaProxy(arg1:boolean):Promise<void>;

export function SetProxyConfig(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<boolean>;

export function SetTrafficLogging(arg1:boolean):Promise<void>;

export function Start():Promise<boolean>;

export function Stop():Promise<boolean>;

export function TestConnection(arg1:string,arg2:number):Promise<string>;
